# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kubetunnel < Formula
  desc "Develop microservices locally while being connected to your kubernetes environme"
  homepage "https://github.com/we-dcode/kubetunnel"
  url "https://github.com/we-dcode/kubetunnel/archive/test-release-4.tar.gz"
  sha256 "c640fdff43ed3037d710346770e8253cc7e2f9f639ef4f7ac7a850f05f822deb"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.1.0/kubetunnel--darwin-amd64.tar.gz"
    end
    on_arm do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.1.0/kubetunnel--darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.1.0/kubetunnel--linux-amd64.tar.gz"
    end
  end

  def install
    bin.install "kubetunnel"
  end
end
