# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kubetunnel < Formula
  desc "Develop microservices locally while being connected to your kubernetes environme"
  homepage "https://github.com/we-dcode/kubetunnel"
  url "https://github.com/we-dcode/kubetunnel/archive/test-release-4.tar.gz"
  sha256 "76569b8530eeeef2c0291b231df5aa2bd9842fed9726dcae10325f4efe330aa0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.3.0/kubetunnel--darwin-amd64.tar.gz"
    end
    on_arm do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.3.0/kubetunnel--darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/we-dcode/kubetunnel/releases/download/kubetunnel-cli-0.3.0/kubetunnel--linux-amd64.tar.gz"
    end
  end

  def install
    bin.install "kubetunnel"
  end
    
  def post_install
    ohai "*************************************************"
    ohai "*                                               *"
    ohai "* The KubeTunnel CLI installation has finished. *"
    ohai "*                                               *"
    ohai "* To see available commands run the following:  *"
    ohai "*     kubetunnel --help                         *"
    ohai "*                                               *"
    ohai "*************************************************"
  end

end
